apps:
  - script: './bin/www'
    exec_mode: 'fork'
    name: 'worker-0'
    env:
      PORT: 3500
      NODE_ENV: production
  - script: 'bin/www'
    exec_mode: 'fork'
    name: 'worker-1'
    env:
      PORT: 3501
      NODE_ENV: production